# Generated by Django - Manual migration for analytics materialized views
"""
Create materialized views for pre-aggregated analytics data.

This migration creates PostgreSQL materialized views to improve performance
of common analytics queries. Views are refreshed asynchronously via Celery
when new data is uploaded.

TD-011: Materialized Views for Query Performance
Expected improvement: 10x for aggregation queries

Views created:
- mv_monthly_category_spend: Monthly spend by category
- mv_monthly_supplier_spend: Monthly spend by supplier
- mv_daily_transaction_summary: Daily transaction summaries

Note: This migration is PostgreSQL-only. SQLite (used in tests) will skip these operations.
"""

from django.db import migrations


def create_materialized_views(apps, schema_editor):
    """Create materialized views (PostgreSQL only)."""
    # Skip for non-PostgreSQL databases (e.g., SQLite in tests)
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        # Monthly spend aggregated by category
        cursor.execute("""
            CREATE MATERIALIZED VIEW IF NOT EXISTS mv_monthly_category_spend AS
            SELECT
                organization_id,
                category_id,
                DATE_TRUNC('month', date) AS month,
                SUM(amount) AS total_spend,
                COUNT(*) AS transaction_count,
                AVG(amount) AS avg_amount,
                MIN(amount) AS min_amount,
                MAX(amount) AS max_amount
            FROM procurement_transaction
            GROUP BY organization_id, category_id, DATE_TRUNC('month', date);
        """)

        cursor.execute("""
            CREATE UNIQUE INDEX IF NOT EXISTS mv_monthly_category_spend_idx
            ON mv_monthly_category_spend (organization_id, category_id, month);
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS mv_monthly_category_spend_org_idx
            ON mv_monthly_category_spend (organization_id);
        """)

        # Monthly spend aggregated by supplier
        cursor.execute("""
            CREATE MATERIALIZED VIEW IF NOT EXISTS mv_monthly_supplier_spend AS
            SELECT
                organization_id,
                supplier_id,
                DATE_TRUNC('month', date) AS month,
                SUM(amount) AS total_spend,
                COUNT(*) AS transaction_count,
                AVG(amount) AS avg_amount,
                MIN(amount) AS min_amount,
                MAX(amount) AS max_amount
            FROM procurement_transaction
            GROUP BY organization_id, supplier_id, DATE_TRUNC('month', date);
        """)

        cursor.execute("""
            CREATE UNIQUE INDEX IF NOT EXISTS mv_monthly_supplier_spend_idx
            ON mv_monthly_supplier_spend (organization_id, supplier_id, month);
        """)

        cursor.execute("""
            CREATE INDEX IF NOT EXISTS mv_monthly_supplier_spend_org_idx
            ON mv_monthly_supplier_spend (organization_id);
        """)

        # Daily transaction summary for trend analysis
        cursor.execute("""
            CREATE MATERIALIZED VIEW IF NOT EXISTS mv_daily_transaction_summary AS
            SELECT
                organization_id,
                DATE(date) AS transaction_date,
                COUNT(*) AS transaction_count,
                SUM(amount) AS total_spend,
                AVG(amount) AS avg_amount,
                COUNT(DISTINCT supplier_id) AS unique_suppliers,
                COUNT(DISTINCT category_id) AS unique_categories
            FROM procurement_transaction
            GROUP BY organization_id, DATE(date);
        """)

        cursor.execute("""
            CREATE UNIQUE INDEX IF NOT EXISTS mv_daily_transaction_summary_idx
            ON mv_daily_transaction_summary (organization_id, transaction_date);
        """)


def drop_materialized_views(apps, schema_editor):
    """Drop materialized views (PostgreSQL only)."""
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP MATERIALIZED VIEW IF EXISTS mv_monthly_category_spend CASCADE;")
        cursor.execute("DROP MATERIALIZED VIEW IF EXISTS mv_monthly_supplier_spend CASCADE;")
        cursor.execute("DROP MATERIALIZED VIEW IF EXISTS mv_daily_transaction_summary CASCADE;")


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_add_analytics_composite_indexes'),
    ]

    operations = [
        migrations.RunPython(create_materialized_views, drop_materialized_views),
    ]
