# Generated by Django 5.0.1 on 2026-01-09 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_create_materialized_views'),
        ('authentication', '0008_add_insight_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_id', models.CharField(db_index=True, max_length=36)),
                ('insight_type', models.CharField(db_index=True, max_length=50)),
                ('insight_title', models.CharField(max_length=200)),
                ('insight_severity', models.CharField(max_length=20)),
                ('predicted_savings', models.DecimalField(blank=True, decimal_places=2, help_text='Predicted savings amount from the insight', max_digits=12, null=True)),
                ('action_taken', models.CharField(choices=[('implemented', 'Implemented'), ('dismissed', 'Dismissed'), ('deferred', 'Deferred for Later'), ('investigating', 'Under Investigation'), ('partial', 'Partially Implemented')], db_index=True, max_length=20)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('action_notes', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('pending', 'Outcome Pending'), ('success', 'Achieved Expected Savings'), ('partial_success', 'Partial Savings Achieved'), ('no_change', 'No Measurable Impact'), ('failed', 'Implementation Failed')], db_index=True, default='pending', max_length=20)),
                ('actual_savings', models.DecimalField(blank=True, decimal_places=2, help_text='Actual savings realized after implementation', max_digits=12, null=True)),
                ('outcome_date', models.DateTimeField(blank=True, null=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insight_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_feedback', to='authentication.organization')),
            ],
            options={
                'verbose_name': 'Insight Feedback',
                'verbose_name_plural': 'Insight Feedback',
                'ordering': ['-action_date'],
                'indexes': [models.Index(fields=['organization', 'insight_type'], name='analytics_i_organiz_91f82a_idx'), models.Index(fields=['organization', 'action_taken'], name='analytics_i_organiz_3d0e77_idx'), models.Index(fields=['organization', 'outcome'], name='analytics_i_organiz_8b694e_idx'), models.Index(fields=['action_date'], name='analytics_i_action__24dcd8_idx')],
            },
        ),
    ]
