# Generated by Django 5.0.1 on 2026-01-23 11:39

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_add_insight_feedback'),
        ('authentication', '0009_savings_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('enhance', 'Insight Enhancement'), ('single_insight', 'Single Insight Analysis'), ('deep_analysis', 'Deep Analysis'), ('classify', 'Query Classification'), ('chat', 'Chat Response'), ('health_check', 'Health Check')], db_index=True, max_length=50)),
                ('model_used', models.CharField(db_index=True, max_length=100)),
                ('model_tier', models.CharField(blank=True, choices=[('haiku', 'Haiku (Fast/Cheap)'), ('sonnet', 'Sonnet (Balanced)'), ('opus', 'Opus (Premium)'), ('gpt4o_mini', 'GPT-4o Mini'), ('gpt4_turbo', 'GPT-4 Turbo')], max_length=20, null=True)),
                ('provider', models.CharField(db_index=True, max_length=20)),
                ('tokens_input', models.IntegerField(default=0)),
                ('tokens_output', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=10)),
                ('cache_hit', models.BooleanField(default=False, help_text='Whether response was served from semantic/Redis cache')),
                ('prompt_cache_read_tokens', models.IntegerField(default=0, help_text='Anthropic prompt cache: tokens read from cache')),
                ('prompt_cache_write_tokens', models.IntegerField(default=0, help_text='Anthropic prompt cache: tokens written to cache')),
                ('validation_passed', models.BooleanField(default=True, help_text='Whether LLM response passed hallucination validation')),
                ('validation_errors', models.JSONField(blank=True, default=list, help_text='List of validation errors if validation failed')),
                ('error_occurred', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_requests', to='authentication.organization')),
            ],
            options={
                'verbose_name': 'LLM Request Log',
                'verbose_name_plural': 'LLM Request Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='analytics_l_organiz_c89ac7_idx'), models.Index(fields=['organization', 'request_type'], name='analytics_l_organiz_eee4ae_idx'), models.Index(fields=['provider', 'model_used'], name='analytics_l_provide_bf766f_idx'), models.Index(fields=['created_at'], name='analytics_l_created_1d842d_idx')],
            },
        ),
    ]
