# Generated by Django 5.0.1 on 2026-01-23 11:55

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_add_llm_request_log'),
        ('authentication', '0009_savings_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('enhance', 'Insight Enhancement'), ('single_insight', 'Single Insight Analysis'), ('deep_analysis', 'Deep Analysis'), ('chat', 'Chat Response')], db_index=True, help_text='Type of request this cache entry is for', max_length=50)),
                ('query_text', models.TextField(help_text='Original query/prompt text')),
                ('query_hash', models.CharField(db_index=True, help_text='SHA-256 hash for fast exact-match lookup', max_length=64)),
                ('response_json', models.JSONField(help_text='Cached LLM response')),
                ('hit_count', models.IntegerField(default=0, help_text='Number of times this cache entry was used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('query_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='OpenAI text-embedding-3-small vector (1536 dims)', null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_cache_entries', to='authentication.organization')),
            ],
            options={
                'verbose_name': 'Semantic Cache Entry',
                'verbose_name_plural': 'Semantic Cache Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'request_type', 'expires_at'], name='analytics_s_organiz_22477f_idx'), models.Index(fields=['organization', 'query_hash'], name='analytics_s_organiz_da0842_idx'), models.Index(fields=['expires_at'], name='analytics_s_expires_82ed1f_idx')],
            },
        ),
    ]
