# Generated by Django 5.0.1 on 2026-01-23 14:17

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_add_semantic_cache'),
        ('authentication', '0009_savings_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('supplier_profile', 'Supplier Profile'), ('contract', 'Contract'), ('policy', 'Procurement Policy'), ('best_practice', 'Best Practice'), ('historical_insight', 'Historical Insight')], db_index=True, help_text='Type of document for filtering during retrieval', max_length=50)),
                ('title', models.CharField(help_text='Document title for display', max_length=255)),
                ('content', models.TextField(help_text='Full document content (will be chunked if too long)')),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 hash for deduplication', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (supplier_id, category_id, etc.)')),
                ('source_model', models.CharField(blank=True, help_text="Source Django model if auto-generated (e.g., 'Supplier', 'InsightFeedback')", max_length=100)),
                ('source_id', models.CharField(blank=True, db_index=True, help_text='Source object ID for updates', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete - inactive docs excluded from search')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='OpenAI text-embedding-3-small vector (1536 dims)', null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedded_documents', to='authentication.organization')),
            ],
            options={
                'verbose_name': 'Embedded Document',
                'verbose_name_plural': 'Embedded Documents',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['organization', 'document_type'], name='analytics_e_organiz_b38e8d_idx'), models.Index(fields=['organization', 'is_active'], name='analytics_e_organiz_aadb14_idx'), models.Index(fields=['source_model', 'source_id'], name='analytics_e_source__995bd6_idx'), models.Index(fields=['content_hash'], name='analytics_e_content_de2a89_idx')],
            },
        ),
    ]
