# Generated by Django 5.0.1 on 2025-12-30 20:27

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('procurement', '0002_transaction_unique_transaction_with_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['uuid'], name='procurement_uuid_90acc2_idx'),
        ),
        migrations.AddIndex(
            model_name='dataupload',
            index=models.Index(fields=['uuid'], name='procurement_uuid_98f3a7_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['uuid'], name='procurement_uuid_c157b3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['uuid'], name='procurement_uuid_05aac4_idx'),
        ),
    ]
