# Generated by Django 5.0.1 on 2026-01-05 22:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_preferences_to_userprofile'),
        ('procurement', '0003_category_uuid_dataupload_original_file_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rules', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_policies', to='authentication.organization')),
            ],
            options={
                'verbose_name_plural': 'Spending policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PolicyViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('violation_type', models.CharField(choices=[('amount_exceeded', 'Amount Exceeded'), ('non_preferred_supplier', 'Non-Preferred Supplier'), ('restricted_category', 'Restricted Category'), ('no_contract', 'No Contract Coverage'), ('approval_missing', 'Approval Missing')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_violations', to='authentication.organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_violations', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='procurement.transaction')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='procurement.spendingpolicy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('contract_number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('annual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('renewal_notice_days', models.IntegerField(default=90)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expiring', 'Expiring Soon'), ('expired', 'Expired'), ('renewed', 'Renewed'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('auto_renew', models.BooleanField(default=False)),
                ('upload_batch', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='contracts', to='procurement.category')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='authentication.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='procurement.supplier')),
            ],
            options={
                'ordering': ['end_date'],
                'indexes': [models.Index(fields=['organization', 'end_date'], name='procurement_organiz_f382c6_idx'), models.Index(fields=['organization', 'supplier'], name='procurement_organiz_2f939a_idx'), models.Index(fields=['organization', 'status'], name='procurement_organiz_1009fa_idx'), models.Index(fields=['uuid'], name='procurement_uuid_e1d11f_idx')],
                'unique_together': {('organization', 'contract_number')},
            },
        ),
        migrations.AddIndex(
            model_name='spendingpolicy',
            index=models.Index(fields=['organization', 'is_active'], name='procurement_organiz_71affe_idx'),
        ),
        migrations.AddIndex(
            model_name='spendingpolicy',
            index=models.Index(fields=['uuid'], name='procurement_uuid_9d8a0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='spendingpolicy',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='policyviolation',
            index=models.Index(fields=['organization', '-created_at'], name='procurement_organiz_5d07fd_idx'),
        ),
        migrations.AddIndex(
            model_name='policyviolation',
            index=models.Index(fields=['organization', 'is_resolved'], name='procurement_organiz_15da9c_idx'),
        ),
        migrations.AddIndex(
            model_name='policyviolation',
            index=models.Index(fields=['organization', 'severity'], name='procurement_organiz_4a073e_idx'),
        ),
        migrations.AddIndex(
            model_name='policyviolation',
            index=models.Index(fields=['uuid'], name='procurement_uuid_9356ed_idx'),
        ),
    ]
