# Generated by Django 5.0.1 on 2026-01-06 01:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_column_mapping_and_upload_extensions'),
        ('procurement', '0004_add_contract_policy_violation_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupload',
            name='celery_task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='column_mapping_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='processing_mode',
            field=models.CharField(choices=[('sync', 'Synchronous'), ('async', 'Asynchronous')], default='sync', max_length=10),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='progress_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='progress_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='stored_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='dataupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='processing', max_length=20),
        ),
        migrations.CreateModel(
            name='ColumnMappingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('mapping', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mapping_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_templates', to='authentication.organization')),
            ],
            options={
                'verbose_name': 'Column Mapping Template',
                'verbose_name_plural': 'Column Mapping Templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='dataupload',
            name='column_mapping_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='procurement.columnmappingtemplate'),
        ),
        migrations.AddIndex(
            model_name='dataupload',
            index=models.Index(fields=['celery_task_id'], name='procurement_celery__ba3b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='dataupload',
            index=models.Index(fields=['status'], name='procurement_status_3062e5_idx'),
        ),
        migrations.AddIndex(
            model_name='columnmappingtemplate',
            index=models.Index(fields=['organization', 'is_default'], name='procurement_organiz_406366_idx'),
        ),
        migrations.AddIndex(
            model_name='columnmappingtemplate',
            index=models.Index(fields=['uuid'], name='procurement_uuid_9147b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='columnmappingtemplate',
            unique_together={('organization', 'name')},
        ),
    ]
