# Generated by Django 5.0.1 on 2026-01-07 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_add_organization_branding_fields'),
        ('procurement', '0005_add_column_mapping_and_upload_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('po_number', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('freight_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_contract_backed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('sent_to_supplier', 'Sent to Supplier'), ('acknowledged', 'Acknowledged'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_date', models.DateField()),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('required_date', models.DateField(blank=True, null=True)),
                ('promised_date', models.DateField(blank=True, null=True)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amendment_count', models.PositiveIntegerField(default=0)),
                ('upload_batch', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='procurement.category')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='procurement.contract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='authentication.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('gr_number', models.CharField(max_length=50)),
                ('received_date', models.DateField()),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantity_accepted', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending Inspection'), ('accepted', 'Accepted'), ('partial_accept', 'Partially Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('inspection_notes', models.TextField(blank=True)),
                ('upload_batch', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='authentication.organization')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_received', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='procurement.purchaseorder')),
            ],
            options={
                'verbose_name': 'Goods Receipt',
                'verbose_name_plural': 'Goods Receipts',
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('pr_number', models.CharField(max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('cost_center', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('budget_code', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted_to_po', 'Converted to PO'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('created_date', models.DateField()),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('rejection_date', models.DateField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('upload_batch', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requisitions', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='procurement.category')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requisitions', to='authentication.organization')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_created', to=settings.AUTH_USER_MODEL)),
                ('supplier_suggested', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_requisitions', to='procurement.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Requisition',
                'verbose_name_plural': 'Purchase Requisitions',
                'ordering': ['-created_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='procurement.purchaserequisition'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_terms', models.CharField(blank=True, max_length=50)),
                ('payment_terms_days', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_days', models.PositiveIntegerField(blank=True, null=True)),
                ('invoice_date', models.DateField()),
                ('received_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('pending_match', 'Pending Match'), ('matched', 'Matched'), ('exception', 'Exception'), ('approved', 'Approved for Payment'), ('on_hold', 'On Hold'), ('paid', 'Paid'), ('disputed', 'Disputed')], default='received', max_length=20)),
                ('match_status', models.CharField(choices=[('unmatched', 'Unmatched'), ('2way_matched', '2-Way Matched'), ('3way_matched', '3-Way Matched'), ('exception', 'Match Exception')], default='unmatched', max_length=20)),
                ('has_exception', models.BooleanField(default=False)),
                ('exception_type', models.CharField(blank=True, choices=[('price_variance', 'Price Variance'), ('quantity_variance', 'Quantity Variance'), ('no_po', 'No Purchase Order'), ('duplicate', 'Duplicate Invoice'), ('missing_gr', 'Missing Goods Receipt'), ('other', 'Other')], max_length=20)),
                ('exception_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('exception_notes', models.TextField(blank=True)),
                ('exception_resolved', models.BooleanField(default=False)),
                ('exception_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('hold_reason', models.TextField(blank=True)),
                ('upload_batch', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exception_resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_invoice_exceptions', to=settings.AUTH_USER_MODEL)),
                ('goods_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='procurement.goodsreceipt')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='authentication.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='procurement.supplier')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='procurement.purchaseorder')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-invoice_date', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='procurement_organiz_6af0c7_idx'), models.Index(fields=['organization', 'match_status'], name='procurement_organiz_c2e775_idx'), models.Index(fields=['organization', 'due_date'], name='procurement_organiz_9d12c3_idx'), models.Index(fields=['organization', 'supplier'], name='procurement_organiz_e37e7f_idx'), models.Index(fields=['organization', 'has_exception'], name='procurement_organiz_d9b787_idx'), models.Index(fields=['organization', 'invoice_date'], name='procurement_organiz_587d53_idx'), models.Index(fields=['uuid'], name='procurement_uuid_8649b1_idx'), models.Index(fields=['upload_batch'], name='procurement_upload__5bf7f5_idx')],
                'unique_together': {('organization', 'invoice_number', 'supplier')},
            },
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['organization', 'status'], name='procurement_organiz_361ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['organization', 'received_date'], name='procurement_organiz_d0a000_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['organization', 'purchase_order'], name='procurement_organiz_0c4b02_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['uuid'], name='procurement_uuid_a1d4c2_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['upload_batch'], name='procurement_upload__797cb4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='goodsreceipt',
            unique_together={('organization', 'gr_number')},
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['organization', 'status'], name='procurement_organiz_cfbcf3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['organization', 'created_date'], name='procurement_organiz_3cf3d4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['organization', 'department'], name='procurement_organiz_7aefc4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['organization', 'priority'], name='procurement_organiz_225cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['uuid'], name='procurement_uuid_cba137_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['upload_batch'], name='procurement_upload__13bb72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaserequisition',
            unique_together={('organization', 'pr_number')},
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['organization', 'status'], name='procurement_organiz_67bb1c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['organization', 'supplier'], name='procurement_organiz_de1d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['organization', 'created_date'], name='procurement_organiz_914a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['organization', 'is_contract_backed'], name='procurement_organiz_29acc8_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['uuid'], name='procurement_uuid_4032bf_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['upload_batch'], name='procurement_upload__fb7a8f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('organization', 'po_number')},
        ),
    ]
