# Generated by Django 5.2.14 on 2026-05-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0009_cross_org_fk_check_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataupload",
            name="last_processed_batch_index",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
