"""
Drop redundant indexes (v3.0 Phase 3 task 3.6 / M-DB5 + M-DB6).

Two classes of redundancy across procurement models:

1. UUID columns triple-indexed: `unique=True` (creates unique btree),
   `db_index=True` (adds a 2nd btree), and an explicit Index(fields=['uuid'])
   in Meta.indexes (a 3rd btree). Keep only the unique index; drop the others.

2. `unique_together = ('organization', 'name')` already creates a unique
   btree index that serves left-prefix lookups. Explicit
   Index(fields=['organization', 'name']) on Supplier / Category was a
   duplicate covering the same column set.

Pure churn: zero behavior change. Postgres DROP INDEX is fast and reversible
(reverse migration restores the indexes if rolled back).
"""

# Generated by Django 5.2.14 on 2026-05-07 01:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0010_dataupload_last_processed_batch_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="category",
            name="procurement_organiz_05eb76_idx",
        ),
        migrations.RemoveIndex(
            model_name="category",
            name="procurement_uuid_90acc2_idx",
        ),
        migrations.RemoveIndex(
            model_name="columnmappingtemplate",
            name="procurement_uuid_9147b4_idx",
        ),
        migrations.RemoveIndex(
            model_name="contract",
            name="procurement_uuid_e1d11f_idx",
        ),
        migrations.RemoveIndex(
            model_name="dataupload",
            name="procurement_uuid_98f3a7_idx",
        ),
        migrations.RemoveIndex(
            model_name="goodsreceipt",
            name="procurement_uuid_a1d4c2_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoice",
            name="procurement_uuid_8649b1_idx",
        ),
        migrations.RemoveIndex(
            model_name="policyviolation",
            name="procurement_uuid_9356ed_idx",
        ),
        migrations.RemoveIndex(
            model_name="purchaseorder",
            name="procurement_uuid_4032bf_idx",
        ),
        migrations.RemoveIndex(
            model_name="purchaserequisition",
            name="procurement_uuid_cba137_idx",
        ),
        migrations.RemoveIndex(
            model_name="spendingpolicy",
            name="procurement_uuid_9d8a0c_idx",
        ),
        migrations.RemoveIndex(
            model_name="supplier",
            name="procurement_organiz_a3bcf3_idx",
        ),
        migrations.RemoveIndex(
            model_name="supplier",
            name="procurement_uuid_c157b3_idx",
        ),
        migrations.RemoveIndex(
            model_name="transaction",
            name="procurement_uuid_05aac4_idx",
        ),
        migrations.AlterField(
            model_name="category",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="columnmappingtemplate",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="dataupload",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="goodsreceipt",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="policyviolation",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="purchaserequisition",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="spendingpolicy",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
