# Generated by Django 5.0.1 on 2025-12-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='User preferences (theme, notifications, etc.)'),
        ),
    ]
