# Generated by Django 5.0.1 on 2026-01-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_preferences_to_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('upload', 'Upload'), ('export', 'Export'), ('view', 'View'), ('reset', 'Reset'), ('bulk_delete', 'Bulk Delete')], max_length=20),
        ),
    ]
