# Generated by Django 5.0.1 on 2026-01-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_column_mapping_and_upload_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Organization logo for reports (recommended: 200x60px PNG)', null=True, upload_to='org_logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(default='#1e3a5f', help_text='Primary brand color in hex format (e.g., #1e3a5f)', max_length=7),
        ),
        migrations.AddField(
            model_name='organization',
            name='report_footer',
            field=models.TextField(blank=True, default='', help_text='Custom footer text for reports (e.g., confidentiality notice)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='secondary_color',
            field=models.CharField(default='#2563eb', help_text='Secondary brand color in hex format (e.g., #2563eb)', max_length=7),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, help_text='Organization website URL'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('upload', 'Upload'), ('export', 'Export'), ('download', 'Download'), ('view', 'View'), ('reset', 'Reset'), ('bulk_delete', 'Bulk Delete'), ('generate', 'Generate')], max_length=20),
        ),
    ]
