# Generated by Django 5.0.1 on 2026-01-08 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_migrate_existing_memberships'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userorganizationmembership',
            new_name='authenticat_user_id_fe36ed_idx',
            old_name='authenticat_user_id_7c5f3e_idx',
        ),
        migrations.RenameIndex(
            model_name='userorganizationmembership',
            new_name='authenticat_organiz_af11cc_idx',
            old_name='authenticat_organiz_3a8b2c_idx',
        ),
        migrations.AlterField(
            model_name='userorganizationmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_memberships', to='authentication.organization'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='authentication.organization'),
        ),
    ]
