# Generated by Django 5.0.1 on 2026-01-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_add_insight_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='savings_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configurable savings rates for AI Insights (industry benchmarks)'),
        ),
    ]
