# Generated by Django 5.0.1 on 2026-01-07 11:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_add_column_mapping_and_upload_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('spend_analysis', 'Spend Analysis'), ('supplier_performance', 'Supplier Performance'), ('savings_opportunities', 'Savings Opportunities'), ('price_trends', 'Price Trends'), ('contract_compliance', 'Contract Compliance'), ('executive_summary', 'Executive Summary'), ('pareto_analysis', 'Pareto Analysis'), ('custom', 'Custom Report')], max_length=50)),
                ('report_format', models.CharField(choices=[('pdf', 'PDF Document'), ('xlsx', 'Excel Spreadsheet'), ('csv', 'CSV File')], default='pdf', max_length=20)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('scheduled', 'Scheduled')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('summary_data', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='authentication.organization')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'report_type'], name='reports_organiz_987b4c_idx'), models.Index(fields=['created_by'], name='reports_created_898775_idx'), models.Index(fields=['status'], name='reports_status_e83c1d_idx'), models.Index(fields=['is_scheduled', 'next_run'], name='reports_is_sche_31f284_idx')],
            },
        ),
    ]
